### ISSUE TITLE
Crashing if Enable Force Feedback,Force Feedback Pass Through, or Pass Through is selected.

### ISSUE THREAD

**Issue by mortar-and-pestle** [x360ce/x360ce#1027]
I am on version 3.2.10.82 using a Xbox One Elite controller and the Microsoft Wireless Receiver. Windows 10. Selecting either option causes an error sound and Xboxce crashes. Is there an error log being generated to see exactly what the issue is? Thanks.

**Comment by mortar-and-pestle** [comment]
Interesting thing I noticed is once I turned the controller off, I received a Microsoft .Net Framework unhandled exception. Maybe related?

Here is some of it:

System.Exception: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SharpDX.XInput.XInput.XInputGetState(Int32 dwUserIndex, State& pState)
   at x360ce.App.Controls.PadControl.UpdateForceFeedBack()
   at x360ce.App.MainForm.ReloadLibrary()
   at x360ce.App.MainForm.UpdateForm3()
   at x360ce.App.MainForm.UpdateTimer_Elapsed(Object sender, ElapsedEventArgs

**Comment by mortar-and-pestle** [comment]
Interesting thing I noticed is once I turned the controller off, I received a Microsoft .Net Framework unhandled exception. Maybe related?

Here is some of it:

System.Exception: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SharpDX.XInput.XInput.XInputGetState(Int32 dwUserIndex, State& pState)
   at x360ce.App.Controls.PadControl.UpdateForceFeedBack()
   at x360ce.App.MainForm.ReloadLibrary()
   at x360ce.App.MainForm.UpdateForm3()
   at x360ce.App.MainForm.UpdateTimer_Elapsed(Object sender, ElapsedEventArgs

**Comment by pekul** [comment]
Me too with **Darksiders Genesis**. My controller is only **Generic USB Controller**. I have 3 controllers similar to it (Generic), and I tested all of them. My PC: Win 10, CPU 6 cores 3.5GHz, 12GB RAM, GPU 1050Ti.

**Comment by EvoJocys** [comment]
Sorry for the seven years late answer. The project was dormant from 2020 and has been active again since August 2026.

This report is about the 3.x line, where x360ce was an xinput DLL copied into each game's folder. The current 4.x line works differently: it creates a virtual Xbox 360 controller that every game sees, with nothing copied into game folders. Game-specific problems from the DLL era do not carry over.

The latest release is 4.21 (September 2026): https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
