### ISSUE TITLE
Unable to generate a temporary class  (result=1) error

### ISSUE THREAD

**Issue by levig7299** [x360ce/x360ce#105]
Hello, I've looked around multiple forums, guides, and troubleshooting posts; but I cannot find and answer to my problem. It seems like it's an xinput problem; but the xinput dll is definitely next to the application in the folder.

When i run the x360ce app in the game folder it creates the necessary files then opens up to the 
default page. immediately after that this error pops up.

under the error message i've included my .ini file

Thank you for your time.

This is the error message.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Unable to generate a temporary class (result=1).
error CS0012: The type 'x360ce.Engine.Data.Game' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.Program' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.PadSetting' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, Type[] extraTypes)
   at x360ce.App.Serializer.GetXmlSerializer(Type type)
   at x360ce.App.Serializer.SerializeToXmlFile(Object o, String path, Encoding encoding, Boolean omitXmlDeclaration, Int32 attempts, Int32 waitTime)
   at x360ce.App.SettingsFile.Save()
   at x360ce.App.SettingManager.SaveSetting(Ini ini, String path)
   at x360ce.App.SettingManager.SaveSettings()
   at x360ce.App.MainForm.UpdateTimer_Elapsed(Object sender, ElapsedEventArgs e)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1026 (RTMGDR.030319-1000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
x360ce
    Assembly Version: 3.0.6.39
    Win32 Version: 3.0.6.39
    CodeBase: file:///C:/GOG%20Games/The%20Witcher%203%20Wild%20Hunt/bin/x64/x360ce_x64.exe
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1026 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1002 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1001 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1015 (RTMGDR.030319-1000)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 3.0.6.39
    CodeBase: file:///C:/GOG%20Games/The%20Witcher%203%20Wild%20Hunt/bin/x64/x360ce_x64.exe
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 3.0.6.39
    CodeBase: file:///C:/GOG%20Games/The%20Witcher%203%20Wild%20Hunt/bin/x64/x360ce_x64.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
x360ce.Engine
    Assembly Version: 1.0.0.0
    Win32 Version: 3.0.6.39
    CodeBase: file:///C:/GOG%20Games/The%20Witcher%203%20Wild%20Hunt/bin/x64/x360ce_x64.exe
----------------------------------------
System.Data.Entity
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1026 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1026 (RTMGDR.030319-1000)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.237 (RTMGDR.030319-2300)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
5f3dqhuh
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1026 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
x360ce.Engine.XmlSerializers
    Assembly Version: 1.0.0.0
    Win32 Version: 3.0.6.39
    CodeBase: file:///C:/GOG%20Games/The%20Witcher%203%20Wild%20Hunt/bin/x64/x360ce_x64.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.    
```

Here is the .ini file for x360ce

```
[Options]
UseInitBeep=1
Log=0
Console=0
DebugMode=0
InternetDatabaseUrl=http://www.x360ce.com/webservices/x360ce.asmx
InternetFeatures=1
InternetAutoload=1
AllowOnlyOneCopy=1

[InputHook]
HookMode=1

[Mappings]
PAD1=IG_86e33080020b11e58001444553540000
PAD2=
PAD3=
PAD4=

[PAD1]
[PAD2]
[PAD3]
[PAD4]

[IG_86e33080020b11e58001444553540000]
ProductName=USB Network Joystick
ProductGuid=00060079-0000-0000-0000-504944564944
InstanceGuid=86e33080-020b-11e5-8001-444553540000
AxisToDPadDeadZone=256
AxisToDPad=0
AxisToDPadOffset=0
A=1
B=2
GuideButton=
Back=7
Start=8
X=3
Y=4
D-pad POV=1
D-pad Down=DOWN
D-pad Left=LEFT
D-pad Right=RIGHT
D-pad Up=UP
UseForceFeedback=1
ForcePercent=100
SwapMotor=0
FFBType=0
ControllerType=1
LeftMotorPeriod=60
LeftMotorStrength=100
LeftMotorDirection=0
Left Shoulder=5
Left Analog X AntiDeadZone=0
Left Analog Y AntiDeadZone=0
Left Analog X Linear=0
Left Analog Y Linear=0
Left Analog X=1
Left Analog Y=-2
Left Thumb=9
Left Analog X DeadZone=0
Left Analog Y DeadZone=0
Left Analog Y- Button=0
Left Analog X- Button=0
Left Analog X+ Button=0
Left Analog Y+ Button=0
Left Trigger=x3
Left Trigger DeadZone=0
PassThrough=1
RightMotorPeriod=120
RightMotorStrength=100
RightMotorDirection=0
Right Shoulder=6
Right Analog X AntiDeadZone=0
Right Analog Y AntiDeadZone=0
Right Analog X Linear=0
Right Analog Y Linear=0
Right Analog X=4
Right Analog Y=-5
Right Thumb=10
Right Analog X DeadZone=0
Right Analog Y DeadZone=0
Right Analog Y- Button=0
Right Analog X- Button=0
Right Analog X+ Button=0
Right Analog Y+ Button=0
Right Trigger=x-3
Right Trigger DeadZone=0
A DeadZone=
B DeadZone=
Back DeadZone=
Start DeadZone=
X DeadZone=
Y DeadZone=
Left Thumb DeadZone=
Right Thumb DeadZone=
Left Shoulder DeadZone=
Right Shoulder DeadZone=
AxisToDPadDownDeadZone=
AxisToDPadLeftDeadZone=
AxisToDPadRightDeadZone=
AxisToDPadUpDeadZone=
```

**Comment by Nucleoprotein** [comment]
.NET 4.0 issue, update to .NET 4.5 or use KB2468871
Personally I recommend running Windows Update and install all updates.

**Comment by samgreen** [comment]
http://www.microsoft.com/en-us/download/confirmation.aspx?id=42642
