### ISSUE TITLE
Crash x360ce

### ISSUE THREAD

**Issue by dik08razz** [x360ce/x360ce#1138]
The program started to crash. At first there was an error that the virtual driver was not installed, clicked install and then x360ce began to crash, but before that it worked quietly and there were no errors.
A program was installed that hides gamepads through an emulator, well, in order to completely emulate the x360 controller and now neither launch gamepads nor the emulator itself ...
Version 4.x.x.x generally crashes, 3.2 works, but since I wrote above, the system does not see them because of the program that hides them.

```
Product
Name:	Jocys.com X360 Controller Emulator 4.9.0.0 (TEST)
Machine:	P8H61-M-LX2
Username:	home
Executable:	D:\Dikobrazz\apps\x360ce\x360ce4900.exe
Build Date:	2019-04-22 18:54:44
Exception
Exception Date:	2020-08-03 17:54:03
Target.Type:	Nefarius.ViGEm.Client.ViGEmClient+NativeMethods
Target.Name:	vigem_alloc
DllNotFoundException: Не удается загрузить DLL "vigemclient.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)
System.DllNotFoundException: Не удается загрузить DLL "vigemclient.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)

   at Nefarius.ViGEm.Client.NativeMethods.vigem_alloc()
   at Nefarius.ViGEm.Client.ViGEmClient..ctor(VIGEM_ERROR& VIGEM_ERROR&)

```

```
Product
Name:	Jocys.com X360 Controller Emulator 4.9.0.0 (TEST)
Machine:	P8H61-M-LX2
Username:	home
Executable:	D:\Dikobrazz\apps\x360ce\x360ce4900.exe
Build Date:	2019-04-22 18:54:44
Exception
Exception Date:	2020-08-03 17:54:03
Target.Type:	Nefarius.ViGEm.Client.ViGEmClient+NativeMethods
Target.Name:	vigem_alloc
ErrorType:	
System.DllNotFoundException
ErrorCount:	
1
Config: ErrorLimitMax:	
5
Config: ErrorLimitAge:	
00:05:00
Config: ErrorUseNewStackTrace:	
False
DllNotFoundException: Не удается загрузить DLL "vigemclient.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)
System.DllNotFoundException: Не удается загрузить DLL "vigemclient.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)

   at Nefarius.ViGEm.Client.NativeMethods.vigem_alloc()
   at Nefarius.ViGEm.Client.ViGEmClient..ctor(VIGEM_ERROR& VIGEM_ERROR&)
   at Nefarius.ViGEm.Client.ViGEmClient.isVBusExists(Boolean Boolean)
   at x360ce.App.DInput.DInputHelper.UpdateVirtualDevices(UserGame UserGame)
   at x360ce.App.DInput.DInputHelper.RefreshAll(DirectInput DirectInput, DeviceDetector DeviceDetector)
   at x360ce.App.DInput.DInputHelper.ThreadAction()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext ExecutionContext, ContextCallback ContextCallback, Object Object, Boolean Boolean)
   at System.Threading.ExecutionContext.Run(ExecutionContext ExecutionContext, ContextCallback ContextCallback, Object Object, Boolean Boolean)
   at System.Threading.ExecutionContext.Run(ExecutionContext ExecutionContext, ContextCallback ContextCallback, Object Object)
   at System.Threading.ThreadHelper.ThreadStart()

```

He clearly swears that he cannot load the vigemclient.dll library, since he cannot find it. How can I fix this problem?
Although in /ProgramData/X360CE/temp/ViGEmClient.dll.84A31178 it appears that she needs no mind.

**Comment by EJocys** [comment]
Please, try latest version 4.12.8.0
https://github.com/x360ce/x360ce/releases

**Comment by dik08razz** [comment]
It also crashes, only it does not even give logs

**Comment by dik08razz** [comment]
@EJocys, [4.12](https://youtu.be/WZ8WvA8Q40w) all the same, where to dig? windows no desire to reinstall

**Comment by EJocys** [comment]
@YanTkach: I've updated X360CE and fix issue with writing error details to: c:\ProgramData\X360CE\Errors\

Please, try latest version 4.12.18.0
https://github.com/x360ce/x360ce/releases

If you haven't tried yet, then try to:

1. Close X360CE.exe
2. Rename c:\ProgramData\X360CE to c:\ProgramData\X360CE.bak, which will clear settings.
3. Start X360CE.exe again

**Comment by ryansaied** [comment]
It still does not work.It opens but after a second it closes.Does it work for quantum controller?

**Comment by dik08razz** [comment]
> It still does not work.It opens but after a second it closes.Does it work for quantum controller?

Sorry, but which controller?

**Comment by dik08razz** [comment]
> @YanTkach: I've updated X360CE and fix issue with writing error details to: c:\ProgramData\X360CE\Errors\
> 
> Please, try latest version 4.12.18.0
> https://github.com/x360ce/x360ce/releases
> 
> If you haven't tried yet, then try to:
> 
> 1. Close X360CE.exe
> 2. Rename c:\ProgramData\X360CE to c:\ProgramData\X360CE.bak, which will clear settings.
> 3. Start X360CE.exe again
> 

Well, I'll come home from work and check and throw off the logs

**Comment by dik08razz** [comment]
### x360ce 4.12.18.0 without changes, it also does not swear at vigemclient.dll


```
Product
Name:	Jocys.com X360 Controller Emulator 4.12.18.0 (TEST)
Machine:	P8H61-M-LX2
Username:	home
Executable:	D:\Dikobrazz\apps\x360ce\x360ce412180.exe
Build Date:	2020-08-05 22:02:58
System.DllNotFoundException: Не удается загрузить DLL "vigemclient.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)
Exception Date:	2020-08-06 13:10:27.633
Target.Type:	Nefarius.ViGEm.Client.ViGEmClient+NativeMethods
Target.Name:	vigem_alloc
.TypeName:	
.Source:	x360ce
.HResult:	-2146233052
Target.Declaring.Assembly:	x360ce, Version=4.12.18.0, Culture=neutral, PublicKeyToken=null
StackTrace:	System.DllNotFoundException: Не удается загрузить DLL "vigemclient.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)
   at Nefarius.ViGEm.Client.NativeMethods.vigem_alloc()
   at Nefarius.ViGEm.Client.ViGEmClient..ctor(VIGEM_ERROR& VIGEM_ERROR&)
      D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\ViGEm\Client\ViGEmClient.x360ce.cs, 22:13
```


```
Product
Name:	Jocys.com X360 Controller Emulator 4.12.18.0 (TEST)
Machine:	P8H61-M-LX2
Username:	home
Executable:	D:\Dikobrazz\apps\x360ce\x360ce412180.exe
Build Date:	2020-08-05 22:02:58
System.DllNotFoundException: Не удается загрузить DLL "vigemclient.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)
Exception Date:	2020-08-06 13:10:28.061
Target.Type:	Nefarius.ViGEm.Client.ViGEmClient+NativeMethods
Target.Name:	vigem_alloc
.TypeName:	
.Source:	x360ce
.HResult:	-2146233052
Target.Declaring.Assembly:	x360ce, Version=4.12.18.0, Culture=neutral, PublicKeyToken=null
StackTrace:	System.DllNotFoundException: Не удается загрузить DLL "vigemclient.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)
   at Nefarius.ViGEm.Client.NativeMethods.vigem_alloc()
   at Nefarius.ViGEm.Client.ViGEmClient..ctor(VIGEM_ERROR& VIGEM_ERROR&)
      D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\ViGEm\Client\ViGEmClient.x360ce.cs, 22:13
   at Nefarius.ViGEm.Client.ViGEmClient.isVBusExists(Boolean Boolean)
      D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\ViGEm\Client\ViGEmClient.x360ce.cs, 158:17
   at x360ce.App.DInput.DInputHelper.UpdateVirtualDevices(UserGame UserGame)
      D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\Common\DInput\DInputHelper.Step5.VirtualDevices.cs, 27:13
   at x360ce.App.DInput.DInputHelper.RefreshAll(DirectInput DirectInput, DeviceDetector DeviceDetector)
      D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\Common\DInput\DInputHelper.cs, 184:5
   at x360ce.App.DInput.DInputHelper.ThreadAction()
      D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\Common\DInput\DInputHelper.cs, 154:6
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext ExecutionContext, ContextCallback ContextCallback, Object Object, Boolean Boolean)
   at System.Threading.ExecutionContext.Run(ExecutionContext ExecutionContext, ContextCallback ContextCallback, Object Object, Boolean Boolean)
   at System.Threading.ExecutionContext.Run(ExecutionContext ExecutionContext, ContextCallback ContextCallback, Object Object)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by EJocys** [comment]
Thank you.

Please download and install latest "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019":

You can find official download links on Microsoft Page:
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

Direct links:
32-bit: https://aka.ms/vs/16/release/vc_redist.x86.exe
64-bit: https://aka.ms/vs/16/release/vc_redist.x64.exe

You can also find it here:
https://visualstudio.microsoft.com/downloads/
Under "Other Tools and Frameworks", "Microsoft Visual C++ Redistributable for Visual Studio 2019"

If it works then I will show this solution directly in the X360CE app when vigemclient.dll client fails to load.

**Comment by dik08razz** [comment]
Oh, and that launched it and the program stopped crashing. Thank you so much.

**Comment by dik08razz** [comment]
Yeah, now the driver is not installed, just the same ViGEm Bus

```
Product
Name:	Jocys.com X360 Controller Emulator 4.12.18.0 (TEST)
Machine:	P8H61-M-LX2
Username:	home
Executable:	D:\Dikobrazz\apps\x360ce\x360ce412180.exe
Build Date:	2020-08-05 22:02:58
System.Exception: Отказано в доступе
Exception Date:	2020-08-06 14:32:22.886
Target.Type:	JocysCom.ClassLibrary.Processes.MouseHook
Target.Name:	Hook1Procedure
.Source:	x360ce.Engine
.HResult:	-2146233088
Target.Declaring.Assembly:	x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
StackTrace:	System.Exception: Access denied
   at JocysCom.ClassLibrary.Processes.MouseHook.Hook1Procedure(Int32 Int32, IntPtr IntPtr, IntPtr IntPtr)

```

**Comment by dik08razz** [comment]
Problem solved by reboot... Everything works, thanks for the help. This information should get to the FAQ

**Comment by EJocys** [comment]
Thank you. I will update next X360CE release and make sure that it offers to download "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019" automatically if DLL fails to load, so that people won't have to go through this issue.

**Comment by EJocys** [comment]
@YanTkach: Updated X360CE. New version 4.12.23.0 detects missing "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019" properly and offers to install it or open Microsoft page where users can download it. 
Latest X360CE is available here: https://github.com/x360ce/x360ce/releases
