### ISSUE TITLE
Crash on first install of x360ce

### ISSUE THREAD

**Issue by IceLancerSR** [x360ce/x360ce#127]
If folder x360ce doesnt exist in programdata even an empty one , exe will just crash with error that it cannot find gdb in that location
Why it even has to look into that folder it should be making gdb and files in present folder of exe

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\X360CE\x360ce.gdb'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at x360ce.Engine.GameDatabaseManager.SetPrograms(IEnumerable`1 programs, IEnumerable`1 games)
   at x360ce.App.SettingsFile.Save(Boolean updateGameDatabase)
   at x360ce.App.SettingsFile.Load()
   at x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   at x360ce.App.Controls.GameSettingsUserControl..ctor()
   at x360ce.App.MainForm.InitializeComponent()
   at x360ce.App.MainForm..ctor()
   at x360ce.App.Program.Main(String[] args)

**Comment by Squall-Leonhart** [comment]
"Why it even has to look into that folder it should be making gdb and files in present folder of exe"

no it shouldn't, gdb is placed in a the program data directory as a place once, used by all dll's set up.

**Comment by elko123** [comment]
I have the same exact problem. I have installed everything that was required I think, .Net, directx, all that. Still can't get it to work.
Any solution?

**Comment by Squall-Leonhart** [comment]
create the folder under c:\programdata\ yourself.

next version will have this fixed.

**Comment by elko123** [comment]
That fixed it, thanks!

**Comment by EJocys** [comment]
fixed. New version available.
