### ISSUE TITLE
System.InvalidOperationException: This access control list is not in canonical form and therefore cannot be modified

### ISSUE THREAD

**Issue by khalidhex** [x360ce/x360ce#1318]
When i try to run the program as administrator it throw this exception 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: This access control list is not in canonical form and therefore cannot be modified.
   at System.Security.AccessControl.CommonAcl.ThrowIfNotCanonical()
   at System.Security.AccessControl.CommonAcl.SetQualifiedAce(SecurityIdentifier sid, AceQualifier qualifier, Int32 accessMask, AceFlags flags, ObjectAceFlags objectFlags, Guid objectType, Guid inheritedObjectType)
   at System.Security.AccessControl.DiscretionaryAcl.SetAccess(AccessControlType accessType, SecurityIdentifier sid, Int32 accessMask, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.CommonObjectSecurity.SetAccessRule(AccessRule rule)
   at JocysCom.ClassLibrary.Security.PermissionHelper.SetRights(RegistryKey baseKey, String registryName, RegistryRights rights, SecurityIdentifier sid, Nullable`1 inheritance, Nullable`1 propagation)
   at x360ce.App.ViGEm.HidGuardianHelper.CanModifyRegistry(String registryName, RegistryRights rights, Boolean fix) in D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\ViGEm\HidGuardianHelper.cs:line 319
   at x360ce.App.ViGEm.HidGuardianHelper.CanModifyParameters(Boolean fix) in D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\ViGEm\HidGuardianHelper.cs:line 303
   at x360ce.App.AppHelper.InitializeHidGuardian() in D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\Common\AppHelper.cs:line 348
   at x360ce.App.MainForm.MainForm_Load(Object sender, EventArgs e) in D:\Projects\TocaEdit\x360ce\x360ce.App.Beta\MainForm.cs:line 182
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
x360ce
    Assembly Version: 4.17.15.0
    Win32 Version: 4.17.15.0
    CodeBase: file:///C:/Users/username/Desktop/x360ce.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

**Comment by EvoJocys** [comment]
This looks like it was addressed. From the changelog:

4.19.17 — Added: Settings can be kept in your own user folder, where no other account can lock them.
4.19.17 — Added: Program offers to try again or use your own folder when settings cannot be saved.

Please try 4.21: https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
