### ISSUE TITLE
Crashing with Unreal Engine 5

### ISSUE THREAD

**Issue by 3dcinetv** [x360ce/x360ce#1368]
Hello, I [followed this tutorial ](https://youtu.be/wDn1zJpZi3U?t=181)to use my gamepad with the U5 engine. But it crashes.
This is the error I see when I copy x360ce to Unreal Engine's directory (which is installed on E:/Epic Games/ Unreal Engine 5):
Please help. All my other games run normally except U5.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at x360ce.App.MainForm.MainForm_KeyDown(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
x360ce
    Assembly Version: 3.2.10.82
    Win32 Version: 3.2.10.82
    CodeBase: file:///E:/Program%20Files/Epic%20Games/UE_5.0/Engine/Binaries/Win64/x360ce_x64.exe
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///E:/Program%20Files/Epic%20Games/UE_5.0/Engine/Binaries/Win64/x360ce_x64.exe
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///E:/Program%20Files/Epic%20Games/UE_5.0/Engine/Binaries/Win64/x360ce_x64.exe
----------------------------------------
x360ce.Engine
    Assembly Version: 1.0.0.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///E:/Program%20Files/Epic%20Games/UE_5.0/Engine/Binaries/Win64/x360ce_x64.exe
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data.Entity
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
vJoyInterfaceWrap
    Assembly Version: 0.2.0.5
    Win32 Version: 3.2.10.82
    CodeBase: file:///E:/Program%20Files/Epic%20Games/UE_5.0/Engine/Binaries/Win64/x360ce_x64.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by AlexMrBison** [comment]
try with the latest version, this does not need to be placed in the game folder, only 1 instance works in all games.

New 4.17.15.0 • 2020-11-15

**Comment by 3dcinetv** [comment]
I understand what you mean by not having to install it into every game folder, but what about the games on U4 that I have already installed it with the previous version?
Do I need to clear out my system? 
Also, what's the "latest" x64 version? Have YOU tried it on Unreal 5? ver. 4.17 from 2020, doesn't seem to be compatible with 2022 Unreal engine 5....
This is what I added, still, U5 doesn't do anything with remapping WASD keys...
https://imgur.com/a/FUKpHcP

**Comment by AlexMrBison** [comment]
yes you will have to remove all the old x360ce instances and the dlls created by it, for a good functioning.
I'm not a UE user but I have a lot of games from various platforms and they work very well with only 1 x360ce open.

I recorded a video showing that the x360ce application works.
https://youtu.be/3BD6x08RtfU

**Comment by 3dcinetv** [comment]
I've cleared all my other 360ce copies. Leaving only 1 installed for all my other games AND the one for the U5 directory.
U5 directory DOES NOT ALLOW 360ce to launch normally, and it throws the above error.
Please help.

**Comment by AlexMrBison** [comment]
> I've cleared all my other 360ce copies. Leaving only 1 installed for all my other games AND the one for the U5 directory. U5 directory DOES NOT ALLOW 360ce to launch normally, and it throws the above error. Please help.

do not put x360ce in unreal engine directory, it is installed in any directory and must be run as administrator.

![image](https://user-images.githubusercontent.com/69490499/180794103-715a2801-bfb2-4b57-b9a4-23724497e9e1.png)
like i did. 
mine runs when starting windows.

I created an x360ce.cmd and put it in the boot folder
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup

```
@echo off

:: Xbox 360 Controller Emulator
ECHO ... wait 10 seconds
Timeout 10

start /b "" "D:\Xbox 360 Controller Emulator\x360ce.exe" /WindowState=Minimized

exit

```
![image](https://user-images.githubusercontent.com/69490499/180794535-a1cc0fa5-5516-45d5-9610-6b573e3a9382.png)

**Comment by 3dcinetv** [comment]
I solved the issue. I downloaded the "download for 64x games" from the download buttons. I cleared all the other 360ce installs. I targeted the Unreal engine 5 folder, copied the x360ce to the u5 folder, executed (with U5 closed) and the new .dll required was created as well as the .ini files. 
Restarted the computer.
Relaunched U5 from the x360ce "application tab". Once the U5 launched, I went to project settings>input>and tested "forward" from the game pad, pressing my controller UP pad.
Closed x360ce. Closed U5.
With my gamepad connected, I restarted U5. (without starting x360ce) and now the game pad works when I "play" the viewport.
Problem solved.

**Comment by EvoJocys** [comment]
This looks like it was addressed. From the changelog:

4.17.22 — Fixed: Crash when loading user device capabilities.
4.17.49 — Fixed: Crash while refreshing the mapped device list.
4.18.6 — Fixed: Crash when a controller was unplugged and plugged back in.
4.18.12 — Fixed: Crash while refreshing devices when the device list changed at the same time.
4.18.63 — Fixed: Add button on a controller page could close the program.

Please try 4.21: https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
