### ISSUE TITLE
Won’t allow me to do anything 

### ISSUE THREAD

**Issue by corathegsd** [x360ce/x360ce#1443]
Hello, I have had no issues with this in the past, but when i try and set up my PXN V9 it says this

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NotSupportedException: The given path's format is not supported.
at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
at System.IO.FileInfo..ctor(String fileName)
at x360ce.Engine.Ini..ctor(String fileName)
at x360ce.App.SettingManager.ReadPadSettings(String file, String iniSection, Int32 padIndex)
at x360ce.App.Controls.NewDeviceForm.NextButton_Click(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

x360ce
Assembly Version: 3.2.10.82
Win32 Version: 3.2.10.82
CodeBase: file:///C:/Users/my name/AppData/Local/Roblox/Versions/version-5c0a67db9ef4467a/x360ce_x86.exe

System.Windows.Forms
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Configuration.Install
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll

System
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

SharpDX.DirectInput
Assembly Version: 2.6.3.0
Win32 Version: 3.2.10.82
CodeBase: file:///C:/Users/my name/AppData/Local/Roblox/Versions/version-5c0a67db9ef4467a/x360ce_x86.exe

SharpDX
Assembly Version: 2.6.3.0
Win32 Version: 3.2.10.82
CodeBase: file:///C:/Users/my name/AppData/Local/Roblox/Versions/version-5c0a67db9ef4467a/x360ce_x86.exe

x360ce.Engine
Assembly Version: 1.0.0.0
Win32 Version: 3.2.10.82
CodeBase: file:///C:/Users/my name/AppData/Local/Roblox/Versions/version-5c0a67db9ef4467a/x360ce_x86.exe

System.Xml
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

System.Data.Entity
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll

System.Runtime.Serialization
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.ComponentModel.DataAnnotations
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4161.0
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll

System.Data
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

Microsoft.GeneratedCode
Assembly Version: 1.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
Assembly Version: 1.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
Assembly Version: 1.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
Assembly Version: 1.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Web
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll

Microsoft.GeneratedCode
Assembly Version: 1.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
Assembly Version: 1.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

vJoyInterfaceWrap
Assembly Version: 0.2.0.5
Win32 Version: 3.2.10.82
CodeBase: file:///C:/Users/my name/AppData/Local/Roblox/Versions/version-5c0a67db9ef4467a/x360ce_x86.exe

System.Numerics
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Web.Services
Assembly Version: 4.0.0.0
Win32 Version: 4.8.4161.0 built by: NET48REL1
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll

x360ce.Engine.XmlSerializers
Assembly Version: 1.0.0.0
Win32 Version: 3.2.10.82
CodeBase: file:///C:/Users/my name/AppData/Local/Roblox/Versions/version-5c0a67db9ef4467a/x360ce_x86.exe

I have reset my PC and it did not work, what can I do to fix it

**Comment by EvoJocys** [comment]
This looks like it was addressed. From the changelog:

4.17.22 — Fixed: Crash when loading user device capabilities.
4.17.49 — Fixed: Crash while refreshing the mapped device list.
4.18.6 — Fixed: Crash when a controller was unplugged and plugged back in.
4.18.12 — Fixed: Crash while refreshing devices when the device list changed at the same time.
4.18.63 — Fixed: Add button on a controller page could close the program.

Please try 4.21: https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
