### ISSUE TITLE
App detects the controller but mapping device is Greyed out

### ISSUE THREAD

**Issue by YowhSup** [x360ce/x360ce#1474]
Hi,

I would like to report a problem. Error details attached below:

Product 
Name: Jocys.com X360 Controller Emulator 4.17.15.0 (TEST) 
Machine: DESKTOP-SODAPO0 
Username: wency 
OS Version: Windows 10 Pro 2009 [Version 10.0.22621.2715] 
Executable: C:\Users\wency\Downloads\x360ce\x360ce.exe 
Build Date: 2020-11-16 01:43:55 
 
System.ArgumentException: Process with an Id of 4460 is not running. 
Exception Date: 2023-11-29 10:21:23.677 
Target.Type: System.Diagnostics.Process 
Target.Name: GetProcessById 
.Source: System 
.HResult: -2147024809 (0x80070057) 
ActiveControlPath: /MainForm/ControlPad1/GameControllersButton 
Target.Declaring.Assembly: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 
StackTrace: System.ArgumentException: Process with an Id of 4460 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 Int32, String String)
   at x360ce.Engine.ForegroundWindowHook.GetActiveProcess(Nullable`1 Nullable`1)
   at x360ce.Engine.ForegroundWindowHook.Hook2Procedure(IntPtr IntPtr, UInt32 UInt32, IntPtr IntPtr, Int32 Int32, Int32 Int32, UInt32 UInt32, UInt32 UInt32)

**Comment by EvoJocys** [comment]
This looks like it was addressed. From the changelog:

4.18.63 — Fixed: Add button on a controller page could close the program.
4.18.63 — Fixed: Cancelling the add device window added the devices chosen the time before.

Please try 4.21: https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
