### ISSUE TITLE
Exception! error when launching x360 64-bit exe

### ISSUE THREAD

**Issue by Kaedy** [x360ce/x360ce#219]
![error](https://cloud.githubusercontent.com/assets/13980183/9491929/ae764092-4c25-11e5-8144-7bdd53bbe164.png)

I had no problems launching the previous versions but this one just won't work. Any ideas? I'm sure I've installed every other prerequisites for this program.

Thanks in advance!

**Comment by Squall-Leonhart** [comment]
Permissions on programdata directory or x360ce subdirectory are incorrect.

**Comment by Kaedy** [comment]
I managed to solve this by deleting the x360ce folder in program data. The previous version probably screwed over the new one. Thanks!

**Comment by Squall-Leonhart** [comment]
My theory is that when this folder was originally created, you had launched the application as Administrator as the game you were using it for was in a UAC protected location.

The subsequent start on a new version was not elevated so the GDB was unable to be replaced with the more current version as when folders are created from an elevated application, they are created with respective administrator privileges and not those of the current user account.

Ejocy, does dotnet provide any way to ensure a folder/file creation inherits parent permissions?

**Comment by EJocys** [comment]
I will try to replicate and fix this bug. Solution, probably would be for application to relaunch itself with administrative privileges and fix permissions. For example: add Write/Modify permission for Users group on INI file and etc.

**Comment by Squall-Leonhart** [comment]
Reopening

**Comment by Squall-Leonhart** [comment]
http://stackoverflow.com/questions/12811850/setting-a-files-acl-to-be-inherited or
http://stackoverflow.com/a/2930969

This looks like what i was suggesting.

**Comment by Ompolar** [comment]
@Squall-Leonhart
 What is that? How do i use these code/whatever is that?
I got this problem too on my PC

**Comment by Squall-Leonhart** [comment]
You don't, its for Ejocy to implement in our software.

You can resolve this issue by deleting the x360ce folder under c:\programdata and running the x360ce application atleast once without elevation.

**Comment by Squall-Leonhart** [comment]
Any progress on this ejocy?

**Comment by EJocys** [comment]
@Squall-Leonhart: Done, just now. Need to complete feature with Virtual Joysticks and ability to see all Direct Input devices (https://github.com/x360ce/x360ce/issues/254). Other projects are eating time. I will try to release new version, this weekend.

**Comment by benjaminstubbs999** [comment]
I have the same problem. I'm running windows 7 64bit. Trying to make a Logitech f710 work with Fallout 4. Bethesda support suggested this program. Any help would be great... Its really sucks to wait this long to play this game and then have issues. Thanks!

**Comment by benjaminstubbs999** [comment]
Sorry, I think I have a different problem...

System.InvalidOperationException: Unable to generate a temporary class (result=1).
error CS0012: The type 'x360ce.Engine.Data.Game' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.Program' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.PadSetting' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, Type[] extraTypes)
   at x360ce.App.Serializer.GetXmlSerializer(Type type)
   at x360ce.App.Serializer.SerializeToXmlFile(Object o, String path, Encoding encoding, Boolean omitXmlDeclaration, Int32 attempts, Int32 waitTime)
   at x360ce.App.SettingsFile.Save(Boolean updateGameDatabase)
   at x360ce.App.SettingsFile.Load()
   at x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   at x360ce.App.Controls.GameSettingsUserControl..ctor()
   at x360ce.App.MainForm.InitializeComponent()
   at x360ce.App.MainForm..ctor()
   at x360ce.App.Program.Main(String[] args)

**Comment by Squall-Leonhart** [comment]
It means you did not install the requirements.

**Comment by benjaminstubbs999** [comment]
what dose that mean? What requirements could i be missing? I installed the copy I got from Bethesda.

**Comment by Fuzzy-McBerts** [comment]
@benjaminstubbs999 think it means you need to download and install the files in the requirements section http://www.x360ce.com/

having same issue... hope it works!

**Comment by PARASF** [comment]
@Fuzzy-McBerts i am having the same problem.
i have just purchased a gamepad and i plugged it in my p.c, after that i dowloaded the x360ce but its showing an exception erro. 
please help.me out

**Comment by Fuzzy-McBerts** [comment]
@PARASF make sure you install all the files in the System Requirements section before installing x360ce.  Specifically:

System Requirements

• Windows Vista or newer.
• .NET 3.5 (includes 2.0 and 3.0) - included in Windows 7.
In Windows 8 and 10: Control Panel > Programs and Features > Turn Windows features on or off > enable “.NET Framework 3.5 (includes 2.0 and 3.0)”.
• .NET 4.6 (includes 4.0) - included in Windows 8 and 10.
• DirectX End-User Runtime (June 2010) - Required regardless of OS; .NET MUST be installed prior to the DirectX update.
• Visual C++ Redistributable for Visual Studio 2013 - For x64 systems install both x86 and x64 redistributables.

**Comment by PARASF** [comment]
thanks buddy..it worked.

**Comment by PARASF** [comment]
hey buddy i need ur help !!!

**Comment by olusegvn** [comment]
Try using XOutput. It'll save you the stress.

**Comment by EvoJocys** [comment]
This report is about the 3.x line, where x360ce was an xinput DLL copied into each game's folder. The current 4.x line works differently: it creates a virtual Xbox 360 controller that every game sees, with nothing copied into game folders. Game-specific problems from the DLL era do not carry over.

The latest release is 4.21 (September 2026): https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
