### ISSUE TITLE
Exception! error

### ISSUE THREAD

**Issue by Glebyc** [x360ce/x360ce#267]
System.InvalidOperationException: Unable to generate a temporary class (result=1).
error CS0012: The type 'x360ce.Engine.Data.Game' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.Program' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.PadSetting' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, Type[] extraTypes)
   at x360ce.App.Serializer.GetXmlSerializer(Type type)
   at x360ce.App.Serializer.SerializeToXmlFile(Object o, String path, Encoding encoding, Boolean omitXmlDeclaration, Int32 attempts, Int32 waitTime)
   at x360ce.App.SettingsFile.Save(Boolean updateGameDatabase)
   at x360ce.App.SettingsFile.Load()
   at x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   at x360ce.App.Controls.GameSettingsUserControl..ctor()
   at x360ce.App.MainForm.InitializeComponent()
   at x360ce.App.MainForm..ctor()
   at x360ce.App.Program.Main(String[] args)

Older version 2.0.2.158 work but all games didnt start x360.
Got new PC, Win 7 64, in previous  old PC Win XP - 86 all work fine,

Help me pls

**Comment by Squall-Leonhart** [comment]
caused by not having the dotnet requirements installed

closed

**Comment by Glebyc** [comment]
dotnet ? what this mean?

**Comment by benjaminstubbs999** [comment]
How do I fix this?
