### ISSUE TITLE
EXCEPTION!

### ISSUE THREAD

**Issue by shahbakht** [x360ce/x360ce#457]
System.InvalidOperationException: Unable to generate a temporary class (result=1).
error CS0012: The type 'x360ce.Engine.Data.Game' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.Program' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.PadSetting' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, Type[] extraTypes)
   at x360ce.App.Serializer.GetXmlSerializer(Type type)
   at x360ce.App.Serializer.SerializeToXmlFile(Object o, String path, Encoding encoding, Boolean omitXmlDeclaration, Int32 attempts, Int32 waitTime)
   at x360ce.App.SettingsFile.Save(Boolean updateGameDatabase)
   at x360ce.App.SettingsFile.Load()
   at x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   at x360ce.App.Controls.GameSettingsUserControl..ctor()
   at x360ce.App.MainForm.InitializeComponent()
   at x360ce.App.MainForm..ctor()
   at x360ce.App.Program.Main(String[] args)

Downloaded the requirements and all and still getting this error! PLEASE HELP!

**Comment by caseywatts** [comment]
Hitting the same error. Will update this issue if/when I figure it out :)

**Comment by keiosweb** [comment]
+1, exactly same exception here :(

**Comment by cebtenzzre** [comment]
It looks like it needs .NET 4.6.  4.6.1 and up seem to be broken with the latest winetricks on my system (yeah, not real Windows lol), but 4.6 works.

**Comment by EvoJocys** [comment]
This report is about the 3.x line, where x360ce was an xinput DLL copied into each game's folder. The current 4.x line works differently: it creates a virtual Xbox 360 controller that every game sees, with nothing copied into game folders. Game-specific problems from the DLL era do not carry over.

The latest release is 4.21 (September 2026): https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
