### ISSUE TITLE
Exception when starting Xbox360ce.

### ISSUE THREAD

**Issue by NightShadowVA** [x360ce/x360ce#601]
System.InvalidOperationException: Unable to generate a temporary class (result=1).
error CS0012: The type 'x360ce.Engine.Data.Game' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.Program' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
error CS0012: The type 'x360ce.Engine.Data.PadSetting' is defined in an assembly that is not referenced. You must add a reference to assembly 'x360ce.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, Type[] extraTypes)
   at x360ce.App.Serializer.GetXmlSerializer(Type type)
   at x360ce.App.Serializer.SerializeToXmlFile(Object o, String path, Encoding encoding, Boolean omitXmlDeclaration, Int32 attempts, Int32 waitTime)
   at x360ce.App.SettingsFile.Save(Boolean updateGameDatabase)
   at x360ce.App.SettingsFile.Load()
   at x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   at x360ce.App.Controls.GameSettingsUserControl..ctor()
   at x360ce.App.MainForm.InitializeComponent()
   at x360ce.App.MainForm..ctor()
   at x360ce.App.Program.Main(String[] args)

**Comment by titchgamer** [comment]
I have this issue also? :(

**Comment by jacob005** [comment]
how can i fix it

**Comment by Hyze1337** [comment]
what windows r u useing i was getting same error and fixed it maybe i can help you

**Comment by Hyze1337** [comment]
If you are useing Windows 7 you need to install .net framework 4.6 but you cant without service pack 1 for windows 7 (if you will try install without it you will get Error) for download service pack 1 update windows instructions: https://support.microsoft.com/en-us/help/15090/windows-7-install-service-pack-1-sp1 or just follow these instuctions (i copied it from site :3) 

manually install SP1 from Windows Update:

Select the Start button > All programs > Windows Update.
In the left pane, select Check for updates.
If any important updates are found, select the link to view available updates. In the list of updates, select Service Pack for Microsoft Windows (KB976932) and then select OK. 

Note
If SP1 isn’t listed, you might need to install some other updates before installing SP1. Install any important updates and then follow these steps again to check for SP1.

Select Install updates. Administrator permission required You might be asked for an admin password or to confirm your choice.

**Comment by cebtenzzre** [comment]
Looks to be a dupe of #457.  Anyway, I'll try a newer .NET and see if that fixes it.
(Though TBH you'd think the README would specifically mention the newer .NET if it were actually needed...)

**Comment by EvoJocys** [comment]
This report is about the 3.x line, where x360ce was an xinput DLL copied into each game's folder. The current 4.x line works differently: it creates a virtual Xbox 360 controller that every game sees, with nothing copied into game folders. Game-specific problems from the DLL era do not carry over.

The latest release is 4.21 (September 2026): https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
