### ISSUE TITLE
win10 crash on start

### ISSUE THREAD

**Issue by Ijmir** [x360ce/x360ce#652]
Hey I have win10, redist 10,12,13,15 86&64 versions.
.NET 4.6+. I get the following when starting 86 & 64 versions of the x360ce

```
SharpDX.SharpDXException: HRESULT: [0x80004005], Module: [General], ApiCode: [E_FAIL/Unspecified error], Message: Unspecified error

   at SharpDX.Result.CheckError()
   at SharpDX.DirectInput.DInput.DirectInput8Create(IntPtr hinst, Int32 dwVersion, Guid riidltf, IntPtr& vOutOut, ComObject unkOuterRef)
   at SharpDX.DirectInput.DirectInput..ctor()
   at x360ce.App.MainForm..ctor()
   at x360ce.App.Program.Main(String[] args)
```

**Comment by Squall-Leonhart** [comment]
directx webredist is required too.
