### ISSUE TITLE
Blank Window & Unhandled Exception with Xenia

### ISSUE THREAD

**Issue by Deep-Dish** [x360ce/x360ce#756]
Whenever I open x360ce_64.exe for use with Xenia, an Xbox 360 emulator I'm trying to test compatibility for, I get this blank window, seemingly not being able to detect my joypad. I'm not able to map any buttons obviously, and I can't even see the picture of the controller you'd usually see.

![x360ce_64--blank](https://user-images.githubusercontent.com/37562220/37630117-0bebc9d4-2bb9-11e8-97af-1c4516b31e21.png)

When I tried to use "Alt + Print Screen" to capture the window above, this popped up. It popped up whenever I pressed the Alt button.

![x360ce_64--unhandled exception](https://user-images.githubusercontent.com/37562220/37630182-6a458682-2bb9-11e8-8ab2-6a4d90b216d7.png)

The following is copied and pasted from the details section of that error window:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at x360ce.App.MainForm.MainForm_KeyDown(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
x360ce
    Assembly Version: 3.2.8.77
    Win32 Version: 3.2.8.77
    CodeBase: file:///D:/Games/Emulation/Emulators/Microsoft/Xenia/x360ce_x64.exe
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
```
I've tried the following solutions:

- re-installing the most recent dot net framework(s)
- trying the 32-bit version of x360ce to see if it suggests using the 64-bit version

I'm not sure what to make of all this to be honest. I even tried seeing if I could find an application/program/game that yielded a similar result, and I came up with nothing. I know it's possible to be used with Xenia however. I tried to find some video of it working with Xenia. Lo and behold: https://youtu.be/d9CFmeCLnnI

The user in the video is using the same version of x360ce as well. This video leads me to believe that it's a problem on my end, but I can't figure out what it could be for the life of me.

I've been using x360ce with many programs for a long time now, and I've never had a problem that couldn't be solved. I noticed that people have posted similar issues here on GitHub with a less detailed explanation of what they were trying to do, but no true solution has been found yet. I've done some research outside of GitHub as well and haven't been able to find any solutions. 

If anyone has even an idea to what's happening, please help me out. I'd greatly appreciate it.

**Comment by augugusto** [comment]
i have the same problem. i placed x360 on the root of the mortal kombat x game and it worked great. then moved it to where the exe is and started having this blank issue

**Comment by Blackviking47** [comment]
same problem with my logi F710.

**Comment by ays999** [comment]
i Have The Same Problem ... That Blanc Screen!!!
Please Help

**Comment by EvoJocys** [comment]
Sorry for the eight years late answer. The project was dormant from 2020 and has been active again since August 2026.

This report is about the 3.x line, where x360ce was an xinput DLL copied into each game's folder. The current 4.x line works differently: it creates a virtual Xbox 360 controller that every game sees, with nothing copied into game folders. Game-specific problems from the DLL era do not carry over.

The latest release is 4.21 (September 2026): https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.

**Comment by augugusto** [comment]
Response was so late that I switched to linux
