### ISSUE TITLE
Puyo Puyo tetris

### ISSUE THREAD

**Issue by rayman89** [x360ce/x360ce#825]
When using x360ce on puyo puyo tetris it says that there was an error to use the variant 2 and test again. What is that supposed to mean?

**Comment by KiNGKiMO** [comment]
Looks like a cracked game issue...

Anyways, use the latest alpha with virtual device:
github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by rayman89** [comment]
I have Vjoy installed although I don't really know how to use it. Opening the alpha version gives me the same error and if I press OK it closes the program. If I ignore the error and go to the issues tab there is no install button (might be causue of vjoy?). If I go to controller 1 and then press the add button it does not list anything even though I have 2 generic usb controllers + vjoy.

**Comment by KiNGKiMO** [comment]
Post a screenshot of the error please.

**Comment by rayman89** [comment]
this? 
![image](https://user-images.githubusercontent.com/5449042/42640010-f5ffa174-85b6-11e8-90ae-cc9f4b7e006e.png)

**Comment by KiNGKiMO** [comment]
> If I ignore the error and go to the issues tab there is no install button

I thought you've error starting x360ce alpha.

![image](https://user-images.githubusercontent.com/11393200/42643504-94ca92b8-85f9-11e8-98df-786d54087bad.png)

You can enable "Devices" tab to check available devices.

Also, try to uninstall vjoy... don't run the game until you've your virtual xbox 360 controllers showing and working at control panel (joy.cpl).

**Comment by rayman89** [comment]
Just to clarify the error on my previous message appears when I open x360ce alpha inside the game folder. if I press ok x360ce closes itself but if I dont press OK I can still navigate trough the x360ce UI but doing some stuff makes the program hang (become non responding) going to the options tab does that. I have the devices tab showing though when I go there it's all blank. If I press the refresh button nothing appears.

I tested opening x360ce on a clean folder (only x360ce alpha exe is on that folder) and when I do that no error shows up and going to the devices tab shows this

![image](https://user-images.githubusercontent.com/5449042/42650092-1d0af4b6-85d1-11e8-8f5d-af595bdac40a.png)

after removing vjoy and restarting the pc the last line on the devices (the vjoy line) disappeared. 

On issues tab I still dont see the "install controller" it says all is OK.  

Opening joy.cpl shows this

![image](https://user-images.githubusercontent.com/5449042/42651455-15761326-85d5-11e8-8313-b61cbc553fb2.png)

**Comment by KiNGKiMO** [comment]
![image](https://user-images.githubusercontent.com/11393200/42654121-d3b95cfc-8617-11e8-8da0-a4ab042d5138.png)
At the options tab, what do you see at the Virtual Device area?

**Comment by KiNGKiMO** [comment]
@rayman89 
Can you please post a screenshot of the game folder with x360ce alpha exe? I need to investigate why it doesn't run if it's in another folder (It should not be in a games folder anyways).

Also, can you check log files "C:\ProgramData\X360CE\Errors" for me?

**Comment by KiNGKiMO** [comment]
@EJocys What does x360ce uses winmm.dll for?
This is the cause of x360ce crash above.

**Comment by rayman89** [comment]
All the tutorials say to put the x360ce exe inside the game fodler that automatically detects what game is it. At least that's how it worked for me with other games. 

This is the game folder

![image](https://user-images.githubusercontent.com/5449042/42657234-4349558a-85e7-11e8-9d82-eb83102c8f49.png)

The asas folder is where I've put an other copy of the alpha x360. The 360ce x64 is the stable version and the other x360 in the game folder is the alpha version.

The error folder has a lot of files I moved them to an other folder and tried opening the stable and the alpha version but none of them generated a new error file. 

Most of the old ones say this 
--

Product
Name:	Jocys.com X360 Controller Emulator 4.8.0.14 (TEST)
Machine:	xxx
Username:	xxx
Executable:	x:\xxx\Puyo Puyo Tetris\x360ce.exe
Build Date:	2018-07-06 09:45:30
Exception
Exception Date:	2018-07-11 12:13:13
Target.Type:	System.Xml.Schema.XsdDateTime
Target.Name:	.ctor
FormatException: The string '' is not a valid AllXsd value.System.FormatException: The string '' is not a valid AllXsd value.

   at System.Xml.Schema.XsdDateTime..ctor(String String, XsdDateTimeFlags XsdDateTimeFlags)


other say this
--

Exception
Exception Date:	2018-07-11 12:13:13
Target.Type:	System.RuntimeMethodHandle
Target.Name:	InvokeMethod
InnerException:	

Exception
Exception Date:	2018-07-11 12:13:13
Target.Type:	System.Xml.Schema.XsdDateTime
Target.Name:	.ctor
FormatException: The string '' is not a valid AllXsd value.System.FormatException: The string '' is not a valid AllXsd value.

   at System.Xml.Schema.XsdDateTime..ctor(String String, XsdDateTimeFlags XsdDateTimeFlags)
   at System.Xml.XmlConvert.ToDateTime(String String, XmlDateTimeSerializationMode XmlDateTimeSerializationMode)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettingsData1.Read6_Program(Boolean Boolean, Boolean Boolean)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettingsData1.Read7_SettingsDataOfProgram(Boolean Boolean, Boolean Boolean)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettingsData1.Read8_Data()
TargetInvocationException: Exception has been thrown by the target of an invocation.System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

   at System.RuntimeMethodHandle.InvokeMethod(Object Object, Object[] Object[], Signature Signature, Boolean Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object Object, Object[] Object[], Object[] Object[])
---> FormatException: The string '' is not a valid AllXsd value.System.FormatException: The string '' is not a valid AllXsd value.

   at System.Xml.Schema.XsdDateTime..ctor(String String, XsdDateTimeFlags XsdDateTimeFlags)
   at System.Xml.XmlConvert.ToDateTime(String String, XmlDateTimeSerializationMode XmlDateTimeSerializationMode)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettingsData1.Read6_Program(Boolean Boolean, Boolean Boolean)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettingsData1.Read7_SettingsDataOfProgram(Boolean Boolean, Boolean Boolean)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettingsData1.Read8_Data()


And the ones from the "asas" folder say this
--


Exception

Exception Date:	2018-07-12 12:58:49
Target.Type:	System.IO.__Error
Target.Name:	WinIOError
UnauthorizedAccessException: Access to the path 'C:\Users\xxx\AppData\Local\Temp\trxxlzoq\trxxlzoq.dll' is denied.System.UnauthorizedAccessException: Access to the path 'C:\Users\xxx\AppData\Local\Temp\trxxlzoq\trxxlzoq.dll' is denied.

   at System.IO.__Error.WinIOError(Int32 Int32, String String)

**Comment by rayman89** [comment]
This is the options tab I dont see anything related to virtualization

![image](https://user-images.githubusercontent.com/5449042/42657869-31ed52c6-85e9-11e8-933a-f0c3086772a8.png)

**Comment by rayman89** [comment]
Yes I've found the virtualization options and now I pressed Install there

![image](https://user-images.githubusercontent.com/5449042/42657936-6c624038-85e9-11e8-8730-bc87683c959a.png)

I added in games the puypo puyo exe and went to controller 1 and ticked the Enable 0 mapped devices and the pc made a sound like something was connected. I pressed the game controllers button and now this appears

![image](https://user-images.githubusercontent.com/5449042/42658157-2854ad94-85ea-11e8-9e5d-5c3cc6a8c4d2.png)

I've configured all and it works properly now but if I open the program from inside the game folder that error still happens.

**Comment by KiNGKiMO** [comment]
DO NOT put x360ce in your game folder, Version 4 (Alpha) is totally different from V3 (Which needed to be in each game folder)....

So,
1- Delete V3, and use V4 Alpha.
2- Put V4 in its own folder.
3- Execute V4 and install virtual drivers.
4- Configure (You need only mapping configurations BTW, no need to add your game at games tab or anything ).
5- You can hide your Generic USB Joystick (click the hide checkbox at Devices tab) . This will make other apps see only your new XBOX 360 Controller.

**Comment by rayman89** [comment]
Thank you. It's all working properly now.

**Comment by EvoJocys** [comment]
Sorry for the eight years late answer. The project was dormant from 2020 and has been active again since August 2026.

This report is about the 3.x line, where x360ce was an xinput DLL copied into each game's folder. The current 4.x line works differently: it creates a virtual Xbox 360 controller that every game sees, with nothing copied into game folders. Game-specific problems from the DLL era do not carry over.

The latest release is 4.21 (September 2026): https://github.com/x360ce/x360ce/releases

Closing as part of a tracker clean-up after the 4.21 release. If it still happens on 4.21, reopen this issue with the version and what you see.
