### ISSUE TITLE
Error SetupDiGetDeviceRegistryPropertyW: 122

### ISSUE THREAD

**Issue by Psychophage** [x360ce/x360ce#830]
Hi, I don't know what I'm doing wrong. As far as I know I have all the prerequisites. I will try reinstalling/repairing them all, but I get this error message: 
**Error Calling SetupDiGetDeviceRegistryPropertyW: 122**

This is for GTA 5, I have tried both the X86 and x64, this is on x64, which I believe the game to be. 

Is there anything I'm missing? Please help :) I tried looking this up and haven't found anything similar, but I might have not looked hard enough and if so I'm sorry for asking again. 

I've also tested administrator privelege and compatability. 

The exception text seems to be related to the program, but I'm unsure of what it means. 

**Details:**
```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Error calling SetupDiGetDeviceRegistryPropertyW: 122
   at JocysCom.ClassLibrary.IO.DeviceDetector.GetStringPropertyForDevice(IntPtr deviceInfoSet, SP_DEVINFO_DATA deviceInfoData, SPDRP propId)
   at JocysCom.ClassLibrary.IO.DeviceDetector.GetVidPidRev(IntPtr deviceInfoSet, SP_DEVINFO_DATA deviceInfoData, UInt32& vid, UInt32& pid, UInt32& rev)
   at JocysCom.ClassLibrary.IO.DeviceDetector.GetDeviceInfo(IntPtr deviceInfoSet, SP_DEVINFO_DATA deviceInfoData, String deviceId)
   at JocysCom.ClassLibrary.IO.DeviceDetector.GetDevices(Guid classGuid, DIGCF flags, String deviceId, Int32 vid, Int32 pid, Int32 rev)
   at x360ce.App.MainForm.RefreshCurrentInstances(Boolean forceReload)
   at x360ce.App.MainForm.UpdateForm3()
   at x360ce.App.MainForm.UpdateTimer_Elapsed(Object sender, ElapsedEventArgs e)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
x360ce
    Assembly Version: 3.2.10.82
    Win32 Version: 3.2.10.82
    CodeBase: file:///D:/Games/Steam/steamapps/common/Grand%20Theft%20Auto%20V/x360ce_x64.exe
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///D:/Games/Steam/steamapps/common/Grand%20Theft%20Auto%20V/x360ce_x64.exe
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///D:/Games/Steam/steamapps/common/Grand%20Theft%20Auto%20V/x360ce_x64.exe
----------------------------------------
x360ce.Engine
    Assembly Version: 1.0.0.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///D:/Games/Steam/steamapps/common/Grand%20Theft%20Auto%20V/x360ce_x64.exe
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data.Entity
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
vJoyInterfaceWrap
    Assembly Version: 0.2.0.5
    Win32 Version: 3.2.10.82
    CodeBase: file:///D:/Games/Steam/steamapps/common/Grand%20Theft%20Auto%20V/x360ce_x64.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by Nucleoprotein** [comment]
Try new version from here: https://github.com/x360ce/x360ce/issues/818

**Comment by Psychophage** [comment]
Thank you for fixing my comment, and thank you for your help. It seems the new version has fixed my issue. It doesn't like being open on one of my monitors but that's okay. You're awesome :)

**Comment by tushup** [comment]
Still not working brother. before somedays it was working well and goo. please help

**Comment by Redigo21** [comment]
I have the same problem then I downloaded the older version (more stable) of x360ce from here check this out! https://steamcommunity.com/sharedfiles/filedetails/?id=859052855

**Comment by Nucleoprotein** [comment]
@EJocys 
This seems to be problem in in this function: https://github.com/x360ce/x360ce/blob/136e5441fb1dc922c8f69592a808c0d7724b0740/x360ce.Engine/JocysCom/IO/DeviceDetector.cs#L220

Error 122 is ERROR_INSUFFICIENT_BUFFER, so it seems buffer is too small ... try to add sizeof current char type.

**Comment by gamerpoweredup** [comment]
An older version of  x360ce, 4.10.0.0 solved Error SetupDiGetDeviceRegistryPropertyW: 122 for me:

https://www.youtube.com/watch?v=tCUVL98apUk

**Comment by maduello** [comment]
> @EJocys
> Cela semble être un problème dans cette fonction:
> 
> https://github.com/x360ce/x360ce/blob/136e5441fb1dc922c8f69592a808c0d7724b0740/x360ce.Engine/JocysCom/IO/DeviceDetector.cs#L220
> 
> L'erreur 122 est ERROR_INSUFFICIENT_BUFFER, il semble donc que la mémoire tampon est trop petite ... essayez d'ajouter la taille du type de caractère actuel.

Bonjour, comment faire donc pour libérer la mémoire tampon?

**Comment by Nucleoprotein** [comment]
@EJocys 
`if (outsize > 0)` should be before `var buffer = new byte[outsize];` because is outsize is 0 there ...

**Comment by EJocys** [comment]
It was fixed in v4.13.41.0 (2020-09-10) i.e. code returns empty string if no description:

```cs
// Get buffer size.
uint propertyRegDataType;
uint requiredSize;
var result = NativeMethods.SetupDiGetDeviceRegistryProperty(deviceInfoSet, ref deviceInfoData, (uint)propId, out propertyRegDataType, null, 0, out requiredSize);
if (!result)
{
	var errorCode = Marshal.GetLastWin32Error();
	if (errorCode == ERROR_INVALID_DATA)
		return null;
	// We can safely ignore other errors when retrieving buffer size.
}
// If no description then return;
if (requiredSize <= 0)
	return "";
var buffer = new byte[requiredSize];
// Get data.
result = NativeMethods.SetupDiGetDeviceRegistryProperty(deviceInfoSet, ref deviceInfoData, (uint)propId, out propertyRegDataType, buffer, buffer.Length, out requiredSize);
(uint)propId, out propertyRegDataType, buffer, buffer.Length, out requiredSize);
```

**Comment by olusegvn** [comment]
Try XOutput. It'll save you the stress.

**Comment by MikedaSpike** [comment]
> It was fixed in v4.13.41.0 (2020-09-10) i.e. code returns empty string if no description:
> 
> ```cs
> // Get buffer size.
> uint propertyRegDataType;
> uint requiredSize;
> var result = NativeMethods.SetupDiGetDeviceRegistryProperty(deviceInfoSet, ref deviceInfoData, (uint)propId, out propertyRegDataType, null, 0, out requiredSize);
> if (!result)
> {
> 	var errorCode = Marshal.GetLastWin32Error();
> 	if (errorCode == ERROR_INVALID_DATA)
> 		return null;
> 	// We can safely ignore other errors when retrieving buffer size.
> }
> // If no description then return;
> if (requiredSize <= 0)
> 	return "";
> var buffer = new byte[requiredSize];
> // Get data.
> result = NativeMethods.SetupDiGetDeviceRegistryProperty(deviceInfoSet, ref deviceInfoData, (uint)propId, out propertyRegDataType, buffer, buffer.Length, out requiredSize);
> (uint)propId, out propertyRegDataType, buffer, buffer.Length, out requiredSize);
> ```

@EJocys , Its an old topic, but can you also make the fix for version 3.2 ?
latest version 4 works correct on my Pinball Cabinet, but my front end doesn't want to work with it. 
Version 3.2 always worked, but properly with a Windows update it screwed something and not able to use the xinput1_x.dll anymore. 
I tried to completly reinstall my cabinet with W11 and add all your dependencies, but after pluging in my pinscape controller I directly get the error "system.Exception: Error calling SetupDiGetDeviceRegistryPropertyW: 122"
Or is this something I can check/fix  in registry as well ?

I hope you can fix this, or point me to the regkey where I can make a manual fix

**Comment by Nucleoprotein** [comment]
122 is ERROR_INSUFFICIENT_BUFFER - this can happen, and this is normal operation - SetupDiGetDeviceRegistryPropertyW will return then required buffer size in RequiredSize argument. 
In most cases apps will call this 2 times - one to get the size and secund one to data.

I think i see a problem: 
`var buffer = new byte[requiredSize];`
buffer is to smal as it is WCHAR, you need to multiply it by char type size @EJocys

**Comment by Chain314** [comment]
Did anyone know how to fix it for x360ce 64 bit

**Comment by neosinan** [comment]
I also have the same issue and my guess is, it is about hardware ID of our controllers, 

These are the hardware ID of my controller, Instead of more common VID_XXXX and PID_XXXX formats, my controller looks like the stuff in the bellow. So My guess is, It cant resolve the IDs.


HID\{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011949_PID&0402_REV&0000&Col03
HID\{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&011949_PID&0402&Col03
HID\{00001812-0000-1000-8000-00805f9b34fb}_LOCALMFG&0002&Col03
HID\VID_1949&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

**Comment by upadsamay387** [comment]
Is it possible to get this fix applied to 3.x? v4 is missing emulation for non-gamepad controllers, which is required for certain games.

**Comment by Alexander207** [comment]
I was about to ask the same question!
