### ISSUE TITLE
Right clicking binding drop-down boxes (instead of left click) will cause errors to be thrown

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#946]
Right clicking binding drop-down boxes (instead of left click) will cause errors to be thrown. Happens on both 4.9 and the version d2e46cb which I recently compiled.
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at x360ce.App.Controls.PadControl.DiMenuStrip_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Aidolii** [comment]
When I deleted the C:\ProgramData\X360CE directory this error began to occur with things other than Record. Seems to be an XML-based error?

**Comment by EJocys** [comment]
Hi Aidolii,

Thank you for reporting. I was able to replicate this issue. I will try to fix it in next release.

**Comment by EJocys** [comment]
Fixed menu issue. Prevented opening drop down incorrectly as a context menu. Committed fix and it will be in next release.
